export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  MERCHANT_ADMIN = 'MERCHANT_ADMIN',
  OPERATOR_SALES = 'OPERATOR_SALES',
  OPERATOR_MEAL = 'OPERATOR_MEAL',
  GUARDIAN = 'GUARDIAN',
  STUDENT = 'STUDENT',
  CONSUMER = 'CONSUMER', // Genérico
  
  // Legacy Roles (Compatibilidade)
  GLOBAL_ADMIN = 'GLOBAL_ADMIN',
  OPERATOR_ADMIN = 'OPERATOR_ADMIN',
  CANTEEN_OPERATOR = 'CANTEEN_OPERATOR',
}

export enum ProductType {
  SALE = 'SALE',
  CONSUMPTION = 'CONSUMPTION',
}

export enum TransactionType {
  RECHARGE = 'RECHARGE',
  PURCHASE = 'PURCHASE',
  REFUND = 'REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
}

export enum WalletType {
  STUDENT = 'STUDENT',
  MERCHANT = 'MERCHANT',
  AMBRA = 'AMBRA',
  SCHOOL = 'SCHOOL',
}
