export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  MERCHANT_ADMIN = 'MERCHANT_ADMIN',
  OPERATOR_SALES = 'OPERATOR_SALES',
  OPERATOR_MEAL = 'OPERATOR_MEAL',
  GUARDIAN = 'GUARDIAN',
  STUDENT = 'STUDENT',
  CONSUMER = 'CONSUMER', // Genérico
}

export enum ProductType {
  SALE = 'SALE',
  CONSUMPTION = 'CONSUMPTION',
}

export enum TransactionType {
  RECHARGE = 'RECHARGE',
  PURCHASE = 'PURCHASE',
  REFUND = 'REFUND',
  REFUND_LOCK = 'REFUND_LOCK',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
}

export enum WalletType {
  STUDENT = 'STUDENT',
  MERCHANT = 'MERCHANT',
  AMBRA = 'AMBRA',
  SCHOOL = 'SCHOOL',
}
